name: simple_di_container_provider
description: "A simple DI container provider for Flutter."
version: 0.0.1
homepage: https://github.com/RuslanTsitser/simple_di_container_provider
repository: https://github.com/RuslanTsitser/simple_di_container_provider

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
